# Generated by Django 3.0.1 on 2020-02-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='cena_les',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_pole',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_rok',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='podil',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_celkem',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_les',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_pole',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
