# Generated by Django 3.0.1 on 2020-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='lv',
            field=models.IntegerField(null=True),
        ),
    ]
