# Generated by Django 3.0.1 on 2020-02-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0002_auto_20200206_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majitele',
            name='smazat',
        ),
    ]
