# Generated by Django 3.0.1 on 2020-04-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0002_auto_20200423_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='cena_les',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_pole',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_rok',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='hlasu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='jmeno',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='katastr',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='mesto',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='nevyplaceno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='osobne',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='podil',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='postou',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='poznamka',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='prezence',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='psc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='ulice',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_celkem',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_les',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='v_pole',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='vyplatni',
            field=models.BooleanField(null=True),
        ),
    ]
