# Generated by Django 3.0.1 on 2020-03-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0003_remove_majitele_smazat'),
    ]

    operations = [
        migrations.CreateModel(
            name='nastavena_cena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
