# Generated by Django 3.0.1 on 2020-04-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0003_auto_20200423_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majitele',
            name='cena',
        ),
        migrations.AddField(
            model_name='majitele',
            name='cena_l',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='majitele',
            name='cena_p',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_les',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_pole',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_rok',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
