# Generated by Django 3.0.1 on 2020-03-21 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0004_nastavena_cena'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='nastavena_cena',
            new_name='NastavenaCena',
        ),
    ]
