# Generated by Django 3.0.1 on 2020-04-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0004_auto_20200423_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='cena_l',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_p',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
