# Generated by Django 3.0.1 on 2020-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0005_auto_20200321_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='VypocitanaCena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_pole', models.IntegerField()),
                ('c_les', models.IntegerField()),
                ('c_rok', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='nastavenacena',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
