# Generated by Django 3.0.1 on 2020-03-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0006_auto_20200321_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nastavenacena',
            name='cena',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vypocitanacena',
            name='c_les',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vypocitanacena',
            name='c_pole',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vypocitanacena',
            name='c_rok',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
