# Generated by Django 3.0.1 on 2020-03-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0009_auto_20200326_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='cena_les',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_pole',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='majitele',
            name='cena_rok',
            field=models.IntegerField(),
        ),
    ]
