# Generated by Django 3.0.1 on 2020-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prvni', '0010_auto_20200326_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majitele',
            name='cena',
            field=models.IntegerField(),
        ),
    ]
